# -*- coding: utf-8 -*-
"""Fall2020-CS146-HW4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HAefzTFUIupG5_o8fzv3oKGfHZLCjVAx
"""

# To add your own Drive Run this cell.
# from google.colab import drive
# drive.mount('/content/drive')

"""
Author      : Zeyuan Chen, adapted from Yi-Chieh Wu, Sriram Sankararman
Description : Twitter
"""

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn import metrics 
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.metrics.cluster import adjusted_rand_score

import pandas as pd
### ========== TODO : START ========== ###
# append you own path to the tweeter_df.txt file after "/content/drive/My Drive/"
# i.e. "/content/drive/My Drive/CM146HW4/tweets_df.txt"
# tweets_df = pd.read_csv("/content/drive/My Drive/", index_col = 0)
tweets_df = pd.read_csv("tweets_df.txt", index_col = 0)
### ========== TODO : END ========== ###

X = tweets_df.values[:,:-2]
y = tweets_df.values[:, -2]
movies = tweets_df.values[:, -1]

train_idx = np.where((movies == 1) | (movies == 3))[0]
dev_idx   = np.where(movies == 2)[0]
test_idx  = np.where(movies == 0)[0]

X_train, X_dev, X_test = X[train_idx,], X[dev_idx,], X[test_idx,]
y_train, y_dev, y_test = y[train_idx,], y[dev_idx,], y[test_idx,]

### ========== TODO : START ========== ###
# part 4.1a: show the train and development set f1-score when C is set to 10^-3 10^-2 10^-1 1, 10, 100, 1000
#            This can typically be done in 20 lines or so
Cs = [1e-3, 1e-2, 1e-1, 1, 10, 100, 1000]
f1_trains = []
f1_devs = []
for C in Cs:
    clf = SVC(kernel='linear', C=C)
    clf.fit(X_train, y_train)
    y_train_pred = clf.predict(X_train)
    f1_train = metrics.f1_score(y_train_pred, y_train)
    f1_trains.append(f1_train)
    # print('f1_score for train set C='+str(C)+' is', f1_train)
    y_dev_pred = clf.predict(X_dev)
    f1_dev = metrics.f1_score(y_dev_pred, y_dev)
    f1_devs.append(f1_dev)
    # print('f1_score for dev set C=' + str(C) + ' is', f1_dev)
C_range = 10.0 ** np.arange(-3, 4)
plt.figure()
plt.plot(f1_devs, label="dev f1-score")
plt.plot(f1_trains, label="train f1-score")
plt.title('dev and train f1-score')
plt.xticks(np.arange(8), C_range)
plt.legend()
plt.savefig('dev&train f1-score.png')
print(f1_devs, f1_trains)
### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.1b: select the best model based on development set f1-score 
#            retrain the model on train and dev set
#            test the final model on the test set
#            This can typically be done in 5 lines or so
X_train_dev  = np.append(X_train, X_dev, axis=0)
y_train_dev = np.append(y_train, y_dev)
clf = SVC(kernel='linear', C=1)
clf.fit(X_train_dev, y_train_dev)
y_test_pred = clf.predict(X_test)
f1_test = metrics.f1_score(y_test_pred, y_test)
print(f1_test)


### ========== TODO : END ========== ###

def plot_scatter(embedding_2d, labels, show = True, save_as = None, title = None):
    """
    Visualize 2D data

    Parameters
    --------------------
        embedding_2d   -- numpy array of shape (n,2) samples
        labels         -- numpy array of shape (n,) labels
        show           -- optional boolean indicator on if display the visualziation, default set to True 
        save_as        -- optional string indicating where we should save the figure, default set to None
        title          -- optional string indicating what should be the title, default set to None
    --------------------
        None    
    """
    
    plt.scatter(embedding_2d[:,0], embedding_2d[:,1], c = labels) 
    if title is not None:
        plt.title(title)
    if save_as is not None:
        plt.savefig(save_as)
    if show:
        plt.show()

pca = PCA(n_components=2)
pca.fit(X)
X_embedding = pca.transform(X)

### ========== TODO : START ========== ###
# part 4.2a: visualize the embedding. First color the dots by positive or negative review, then by movies 
#            This can typically be done in 2 lines or so
plt.figure()
plot_scatter(X_embedding, y, save_as='pov neg cluster.png', title='pov neg cluster')
plot_scatter(X_embedding, movies, save_as='movie cluster.png', title='movie cluster')

### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.2b: First color the dots by Kmeans with 4 components, random initialization, 1 iteration, random_state = 2
#            then by GMM with 4 components, random starting point, 1 iteration and random_state = 0
#            report the adjusted rand score for both
#            This can typically be done in 10 lines or so
clt_kmean = KMeans(n_clusters=4, init='random', n_init=1, random_state=2)
clt_kmean.fit(X_embedding)
y_kmean = clt_kmean.predict(X_embedding)
plot_scatter(X_embedding, y_kmean, save_as='KMeans cluster.png', title='KMeans cluster')
print('The adjusted rand score for kmean is', adjusted_rand_score(movies, y_kmean))

clt_gmm = GaussianMixture(n_components=4, random_state=0, init_params='random')
clt_gmm.fit(X_embedding)
y_gmm = clt_gmm.predict(X_embedding)
plot_scatter(X_embedding, y_gmm, save_as='GMM cluster.png', title='GMM cluster')
print('The adjusted rand score for gmm is', adjusted_rand_score(movies, y_gmm))


### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.2c: First color the dots by Kmeans with 4 components, random initialization, 100 iterations, random_state = 2
#            then by GMM with 4 components, random starting point, 100 iterations and random_state = 0
#            report then adjusted rand score for both
#            This can typically be done in 10 lines or so
clt_kmean = KMeans(n_clusters=4, init='random', n_init=100, random_state=2)
clt_kmean.fit(X_embedding)
y_kmean = clt_kmean.predict(X_embedding)
plot_scatter(X_embedding, y_kmean, save_as='KMeans cluster2.png', title='KMeans cluster2')
print('The adjusted rand score for new kmean is', adjusted_rand_score(movies, y_kmean))

clt_gmm = GaussianMixture(n_components=4, random_state=0, init_params='random', n_init=100)
clt_gmm.fit(X_embedding)
y_gmm = clt_gmm.predict(X_embedding)
plot_scatter(X_embedding, y_gmm, save_as='GMM cluster2.png', title='GMM cluster2')
print('The adjusted rand score for new gmm is', adjusted_rand_score(movies, y_gmm))
### ========== TODO : END ========== ###